apiVersion: apps/v1
kind: Deployment
metadata:
  name: episode-01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: episode-01
  template:
    metadata:
      labels:
        app: episode-01
    spec:
      containers:
      - name: backend
        image: muhammedeman14/back:latest
        ports:
        - containerPort: 3000
      - name: frontend
        image: muhammedeman14/front:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
  selector:
    app: episode-01
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
  selector:
    app: episode-01
